### ISSUE TITLE
How do I compile this?

### ISSUE THREAD

**Issue by vskokov** [wwwater/resident-seal#7]
See the subject!

**Comment by wwwater** [comment]
1. Install `qt5` (e.g. `sudo apt-get install qt5-default`) and check that it's installed correctly via `qmake -v` to see that the Qt version is 5.
2. Go into `src` and run the following commands:
``` 
qmake src.pro
make
```
3. Run the exec file in `bin`:
```
 ../bin/resident-seal
```
